version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111111
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      proxynet:

  backend:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always
    networks:
      proxynet:

networks:
  proxynet:
    name: local_network
